apiVersion: v1
kind: Service
metadata:
  name: consul
spec:
  ports:
    - port: 8500
      targetPort: 8500
    - port: 8501
      targetPort: 8501
  selector:
    app: consul
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consul
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: consul
  template:
    metadata:
      labels:
        app: consul
    spec:
      containers:
        - image: consul:1.7
          name: consul
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8500
            - containerPort: 8501
          args:
            - "agent"
            - "-dev"
            - "-ui"
            - "-client=0.0.0.0"
            - "-bind=0.0.0.0"
            - "-https-port=8501"
