apiVersion: v1
kind: Service
metadata:
  name: consul
spec:
  ports:
    - port: 8500
      targetPort: 8500
    - port: 8501
      targetPort: 8501

  selector:
    app: consul
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consul
spec:
  replicas: 1
  revisionHistoryLimit: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mailhog
    spec:
      volumes:
        - name: secrets-volume
          secret:
            secretName: mailhog-login
      containers:
        - name: consul
          image: consul:1.7
          ports:
            - containerPort: 8500
            - containerPort: 8501
          args:
            - "agent"
            - "-dev"
            - "-ui"
            - "-client=0.0.0.0"
            - "-bind=0.0.0.0"
            - "-https-port=8501"